### PR TITLE
Delete `deps/` directory

### PR DESCRIPTION
**Pull request by giordano**
Any reason to keep the `deps/` directory around?  It's largish and unused

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should be deleted since we now have CRlibm_jll. Happy to merge and help cleanup if someone can give me owner access on this org.

**Comment by dpsanders** [comment]
@ViralBShah : I made you an owner of the org, thanks!

**Comment by dpsanders** [comment]
Is `CRlibm_jll` actually being used by this repo already? If not please go ahead and merge that too. I seem to remember there was some minor issue on Win32 but we should just ignore that.

**Comment by ViralBShah** [comment]
Hmm, I didn't know about that. I got a Crlibm_jll today as part of Makie on my mac, so I assumed that was the case everywhere. At least it looks like the win32 binaries do get built: https://github.com/JuliaBinaryWrappers/CRlibm_jll.jl

**Comment by ViralBShah** [comment]
I think the win32 issue is this: https://github.com/JuliaIntervals/CRlibm.jl/issues/45. But at least doesn't have to do with the build. So deps can go...

**Pull request merged**
