### PR TITLE
Use CRlibm_jll

### PR DESCRIPTION
**Pull request by giordano**
Close #38

### CODE REVIEW

**Comment by giordano** [comment]
@dpsanders you need to enable GitHub Actions...

**Comment by dpsanders** [comment]
I think I just enabled GitHub actions. Do I need to do anything else?

Thanks very much for this, @giordano!

**Comment by giordano** [comment]
> Do I need to do anything else?

Since I'm moving all CI to GitHub Actions, if you don't want to see a red mark on all PRs and commits you should also disable Appveyor :slightly_smiling_face:

**Comment by giordano** [comment]
But GitHub Actions still don't start

**Comment by dpsanders** [comment]
Do I need to "Allow all actions"? 
Currently it's set to allow only local actions.

**Comment by giordano** [comment]
> Do I need to "Allow all actions"?

Yes :slightly_smiling_face:

**Comment by dpsanders** [comment]
OK, done, sorry!

**Comment by giordano** [comment]
Still nothing :confused:

**Comment by dpsanders** [comment]
Is it supposed to run already before the PR is merged?

**Comment by giordano** [comment]
Yes

**Comment by giordano** [comment]
Ok, I resuscitated Travis and Appveyor at least to be able to run the tests (provided that Travis works at all), but I suggest moving to GitHub Actions given the recent changes to Travis

**Comment by dpsanders** [comment]
I'm very happy to move to GitHub actions if that's the recommended solution, provided it works...!  Is it just that single "Allow all actions" setting that needs to be changed?

**Comment by giordano** [comment]
Yes, but I'm honestly surprised that you had to do that at all since it should be on by default.  Maybe you have some organisation-level settings blocking GitHub Actions?

**Comment by dpsanders** [comment]
Great job, thanks a lot!

**Pull request merged**
